spring.application.name=zwloader
logging.level.org.springframework.boot.docker.compose=DEBUG


# DB
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres_db:5432/change_me}
spring.datasource.username=${DB_USER:shuffle_app}
spring.datasource.password=${DB_PASSWORD:change_me}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# auth (??? ??????????? basic ???????????? ? ????? ??????? ?? ??????? ??????????)
spring.security.user.name=${APP_ADMIN_USER:change_me}
spring.security.user.password=${APP_ADMIN_PASS:change_me}

# web
server.port=${APP_PORT:8081}

# db init flags
app.db.init.enabled=${DB_INIT_ENABLED:false}
app.db.init.createTypes=${DB_INIT_CREATE_TYPES:false}
app.db.init.useUuidDefault=${DB_INIT_USE_UUID_DEFAULT:false}


# env
#api.home_assistant=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI1NDdhNGM3ZDZhOWQ0OGFiOTNiYzRlMDBlNjY1MDcwYiIsImlhdCI6MTc2MzU2OTE5MiwiZXhwIjoyMDc4OTI5MTkyfQ.zUil22MxzgU4rhYTJBbGMPzcbRjd_WXqxPvFrqTMx_Y

api.compreface=${API_KEY_COMPREFACE:change_me}
# external API endpoints / tokens (???????? ? env)
api.compreface.url=${COMPREFACE_URL:change_me}
# Home Assistant outbound integration settings
api.home_assistant=${HOME_ASSISTANT_TOKEN:change_me}
api.home_assistant.url=${HOME_ASSISTANT_URL:change_me}
# app.ha.webhook-token=${HA_WEBHOOK_TOKEN:change_me}
