CREATE ROLE shuffle_app LOGIN PASSWORD 'changeme';
GRANT USAGE ON SCHEMA public TO shuffle_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO shuffle_app;
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA public TO shuffle_app;

CREATE ROLE shuffle_ro LOGIN PASSWORD 'READ_ONLY_123';
GRANT USAGE ON SCHEMA public TO shuffle_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO shuffle_ro;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO shuffle_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO shuffle_ro;

GRANT CREATE ON SCHEMA public TO shuffle_app;


CREATE EXTENSION IF NOT EXISTS pgcrypto;